name: Unit Tests
on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'bugfix/**'
jobs:
  build_test:
    name: Run tests
    runs-on: macOS-12
    env:
        XCODE_VERSION: "14.0"

    steps:
      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1.57.0
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Run Xcode tests
        run: bundle exec fastlane test