name: iOS Unit Tests
on:
  push:
    branches:
      - 'main'
      - 'feature/**'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bundle exec fastlane test